from typing import Optional, Dict, Any, Tuple, Awaitable

class CipherToken:
    def __init__(self, secret: str, algorithm: str, access_ttl: int, refresh_ttl: int) -> None: ...
    
    # Sync methods
    def access(self, user_id: int, extra_payload: Optional[Dict[str, Any]] = None) -> str: ...
    def refresh(self, user_id: int, extra_payload: Optional[Dict[str, Any]] = None) -> str: ...
    def decode(self, token: str) -> Dict[str, Any]: ...
    def verify(self, token: str) -> bool: ...
    def rotation(self, refresh_token: str, extra_payload: Optional[Dict[str, Any]] = None) -> Tuple[str, str]: ...
    def inspect(self, token: str) -> Dict[str, Any]: ...
    def remaining_time(self, token: str) -> Optional[int]: ...
    def algorithm_name(self) -> str: ...
    
    # Async methods
    async def access_async(self, user_id: int, extra_payload: Optional[Dict[str, Any]] = None) -> Awaitable[str]: ...
    async def refresh_async(self, user_id: int, extra_payload: Optional[Dict[str, Any]] = None) -> Awaitable[str]: ...
    async def decode_async(self, token: str) -> Awaitable[Dict[str, Any]]: ...
    async def verify_async(self, token: str) -> Awaitable[bool]: ...
    async def rotation_async(self, refresh_token: str, extra_payload: Optional[Dict[str, Any]] = None) -> Awaitable[Tuple[str, str]]: ...

# Utility functions
def is_jwt_format(token: str) -> bool: ...
def validate_jwt_format(token: str) -> bool: ...

