from typing import Any, Dict, Optional, Tuple

class CipherToken:
    def __init__(self, secret: str, algorithm: str, access_ttl: int, refresh_ttl: int) -> None: ...

    def payload(self, payload: Optional[Dict[str, Any]] = None) -> str: ...
    def access(self, payload: Optional[Dict[str, Any]] = None) -> str: ...
    def refresh(self, payload: Optional[Dict[str, Any]] = None) -> str: ...
    def decode(self, token: str) -> Dict[str, Any]: ...
    def verify(self, token: str) -> bool: ...
    def rotation(self, refresh_token: str, payload: Optional[Dict[str, Any]] = None) -> Tuple[str, str]: ...
    def inspect(self, token: str) -> Dict[str, Any]: ...
    def remaining_time(self, token: str) -> Optional[int]: ...
    def algorithm_name(self) -> str: ...

    async def access_async(self, payload: Optional[Dict[str, Any]] = None) -> str: ...
    async def refresh_async(self, payload: Optional[Dict[str, Any]] = None) -> str: ...
    async def decode_async(self, token: str) -> Dict[str, Any]: ...
    async def verify_async(self, token: str) -> bool: ...
    async def rotation_async(self, refresh_token: str, payload: Optional[Dict[str, Any]] = None) -> Tuple[str, str]: ...

def is_jwt_format(token: str) -> bool: ...
def validate_jwt_format(token: str) -> bool: ...
