from typing import Any, Dict, Optional, Tuple
from .ciphertoken import CipherToken

TOKEN_ACCESS: str
TOKEN_REFRESH: str

def access(token: CipherToken, payload: Optional[Dict[str, Any]] = None) -> str: ...
def refresh(token: CipherToken, payload: Optional[Dict[str, Any]] = None) -> str: ...
def rotation(token: CipherToken, refresh_token: str, payload: Optional[Dict[str, Any]] = None) -> Tuple[str, str]: ...

async def access_async(token: CipherToken, payload: Optional[Dict[str, Any]] = None) -> str: ...
async def refresh_async(token: CipherToken, payload: Optional[Dict[str, Any]] = None) -> str: ...
async def rotation_async(token: CipherToken, refresh_token: str, payload: Optional[Dict[str, Any]] = None) -> Tuple[str, str]: ...
